import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { SessionProvider } from "@/lib/session";
import { cookies } from "next/headers";
import { AUTH_COOKIE } from "@/lib/core";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SSO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal?: React.ReactNode;
}>) {
  const cookie = cookies();
  const authToken = cookie.get(AUTH_COOKIE);
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider authToken={authToken?.value}>
          {children}
          {modal}
        </SessionProvider>
        <Toaster />
      </body>
    </html>
  );
}
